site_name: Vector Docs
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

nav:
  - Home: index.md
  - Developer Guide:
    - Getting Started: dev-guide/getting-started.md
  - User Guide:
    - What you can do: user-guide/what-you-can-do.md