site_name: Vector Docs
theme:
  name: material
  palette:
    scheme: slate
    primary: green
  logo: img/anki.png
  favicon: img/favicon.png
repo_url: https://github.com/ThommoMC/vector-docs

nav:
  - Home: index.md
  - Developer Guide:
    - Getting Started: dev-guide/getting-started.md
  - User Guide:
    - What you can do: user-guide/what-you-can-do.md